### ISSUE TITLE
Do you get a real system alert with HTTP Basic Auth?

### ISSUE THREAD

**Issue by benzado** [jansoucek/iOS-Mail.app-inject-kit#2]
Currently, your email triggers a redirect to a page with a simulation of a system alert (it's actually just a form drawn within the email).

If the redirect target responds with status 401 and a `WWW-Authenticate` header, does Mail present a standard iOS alert to collect a username and password?

**Comment by jankais3r** [comment]
No. If the redirect link points to a page secured by HTTP Basic Auth, the redirect never happens. But good thinking.
