### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by mike7628** [jansoucek/iOS-Mail.app-inject-kit#6]
I really dont know what im doing, The instructions given suck. I already had to recode the index.php to send it to my server/framework.php. Now im in framework and dont know what to do. Can someone please tell me where to put the victims email in framework.php. And who is "collector". And where do I put that. Not everyone is a skilled coder so can someone help me.

**Comment by jankais3r** [comment]
I am not here to help you scam people. If you don't understand this basic code, you are not the target audience.
