### ISSUE TITLE
No Work, ihpone 4s, IOS 8.4

### ISSUE THREAD

**Issue by goide** [jansoucek/iOS-Mail.app-inject-kit#7]
I followed the steps and did not work me, I come to me empty my inbox.

![photo jul 10 3 25 52 pm](https://cloud.githubusercontent.com/assets/1667283/8628412/6db76df6-2718-11e5-8084-8fa9ce91ddd3.png)

**Comment by jankais3r** [comment]
It was fixed in 8.4.
